sudo: false

language: php

php:
  - 7.3
  - 7.4
  - nightly

matrix:
  allow_failures:
    - php: nightly

cache:
  directories:
    - $HOME/.composer/cache
    - app/vendor

install: composer install

before_script:
  - app/vendor/bin/php-cs-fixer fix --diff --dry-run
  - app/vendor/bin/psalm

script: app/vendor/bin/phpunit --coverage-text
