version: '3.4'

services:
  app:
    container_name: directory-lister-app
    build:
      context: .
      target: development
    environment:
      VIRTUAL_HOST: directorylister.local
    volumes:
      - ./:/var/www/html
      # - ./.docker/php/config/php.dev.ini:/usr/local/etc/php/php.ini
      # - ./.docker/apache2/config/000-default.dev.conf:/etc/apache2/sites-available/000-default.conf
    restart: unless-stopped

networks:
  default:
    external:
      name: development
