version: '3.4'

services:
  apache:
    container_name: directory-lister-apache
    build:
      context: .docker
      dockerfile: Dockerfile.apache
    environment:
      VIRTUAL_HOST: directory-lister.local,directory-lister.apache.local
    volumes:
      - ./:/var/www/html
    restart: unless-stopped

  nginx:
    container_name: directory-lister-nginx
    image: nginx:1.17
    environment:
      VIRTUAL_HOST: directory-lister.nginx.local
    volumes:
      - ./.docker/nginx/config/default.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www/html
    restart: unless-stopped

  php-fpm:
    container_name: directory-lister-php-fpm
    build:
      context: .docker
      dockerfile: Dockerfile.nginx
    volumes:
      - ./:/var/www/html
    restart: unless-stopped

networks:
  default:
    external:
      name: development
